[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax_macros = { path = "./src/macros", optional = true }
syntax_core = { path = "./src/core" }

[[example]]
name = "bplist"

[features]
default = ["macros"]
macros = ["dep:syntax_macros"]
